#!/usr/bin/env bash

namespace=$1
repository=$2
tag=$3
[[ -z "${namespace}" ]] && echo "please provide namespace" && exit
[[ -z "${repository}" ]] && echo "please provide repository" && exit
[[ -z "${tag}" ]] && echo "please provide tag" && exit

mkdir -p ./docker/{images,logs}
docker rmi ${namespace}/${repository}:${tag}
docker build -f Dockerfile.${namespace}.${repository}.${tag} -t ${namespace}/${repository}:${tag} . > ./docker/logs/${namespace}.${repository}.${tag}.log 2>&1
docker save ${namespace}/${repository}:${tag} | gzip > ./docker/images/${namespace}.${repository}.${tag}.tar.gz
