# syntax=docker/dockerfile:1
FROM ubuntu:16.04 AS build
LABEL Description="rdock:2013.1 build"

ENV TZ=America/Chicago \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /app
SHELL ["/bin/bash", "-c"]

COPY ./packages/2013.1/rDock_2013.1_src.tar.gz /app/

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    build-essential cmake gdb wget python3 vim \
    gcc g++ make libpopt-dev libcppunit-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN cd /app && \
    tar -xzf rDock_2013.1_src.tar.gz  && \
    cd ./rDock_2013.1_src/build && \
    make linux-g++-64


FROM ubuntu:16.04 AS runtime
LABEL Description="rdock:2013.1 runtime"

COPY --from=build /app/rDock_2013.1_src /app/rDock_2013.1_src

ENV RBT_ROOT=/app/rDock_2013.1_src/
ENV LD_LIBRARY_PATH=${RBT_ROOT}/lib:${LD_LIBRARY_PATH}
ENV PATH=${RBT_ROOT}/bin:${PATH}

ENV TZ=America/Chicago \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    build-essential cmake gdb wget python3 vim \
    gcc g++ make libpopt-dev libcppunit-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python
    #ln -s /usr/bin/pip3 /usr/bin/pip

WORKDIR /mnt

