#!/usr/bin/env bash

namespace=$1
repository=$2
tag=$3
[[ -z "${namespace}" ]] && echo "please provide namespace" && exit
[[ -z "${repository}" ]] && echo "please provide repository" && exit
[[ -z "${tag}" ]] && echo "please provide tag" && exit

docker rmi ${namespace}/${repository}:${tag}
