#!/usr/bin/env bash
# IMPORTANT - This script is meant to run on a Linux machine
name="rDock"
image_tag="biopod/rdock:2013.1"
script_prefix="rdock"
install_path=/usr/local/bin/

# set some colors
CNT="[\e[1;36mNOTE\e[0m]"
COK="[\e[1;32mOK\e[0m]"
CER="[\e[1;31mERROR\e[0m]"
CAT="[\e[1;37mATTENTION\e[0m]"
CWR="[\e[1;35mWARNING\e[0m]"
CAC="[\e[1;33mACTION\e[0m]"

# set some expectations for the user
echo -e "$CNT - You are about to execute a script that would attempt to setup ${name}."
sleep 1
# get the current folder
current_dir=$(pwd)
if [ ! -d "${current_dir}" ]; then
    echo -e "$CER ${current_dir} does not exist! No changes were made to your system."
    exit
fi

# give the user an option to exit setup
echo -e "$CAT - Image (${image_tag}) will be pulled from Docker Hub and script ${script_prefix}-pod will be installed to the ${install_path}."
read -rep $'[\e[1;33mACTION\e[0m] - Would you like to continue with the setup (y,n) ' CONTINST
if [[ $CONTINST == "Y" || $CONTINST == "y" ]]; then
    echo -e "$CNT - Setup started."
else
    echo -e "$CWR - Aborting setup."
    exit
fi

# pull the image
echo -e "$CNT - Pulling ${image_tag} from Docker Hub."
docker pull ${image_tag}

# install scripts
echo -e "$CNT - Installing ${script_prefix}-pod to ${install_path}."
sed -i '/^image_tag/d' ./bin/${script_prefix}-pod
sed -i "1 aimage_tag=${image_tag}" ./bin/${script_prefix}-pod
sudo cp -a ./bin/${script_prefix}-pod ${install_path} && \
echo -e "$COK - Setup has completed!"
